/*
  # Create quality_control table

  1. New Tables
    - `quality_control`
      - `id` (bigint, primary key, auto-increment)
      - `created_at` (timestamp with time zone, default now())
      - `work_order_id` (text, not null)
      - `check_type` (text, not null)
      - `result` (text, not null, constrained to 'pass', 'fail', 'pending')
      - `inspector` (text, not null)
      - `notes` (text, nullable)
      - `checked_at` (timestamp with time zone, not null)

  2. Security
    - Enable RLS on `quality_control` table
    - Add policies for authenticated and anonymous users to perform CRUD operations

  3. Constraints
    - Check constraint on result field to ensure valid values
*/

-- Create the quality_control table
CREATE TABLE IF NOT EXISTS quality_control (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now() NOT NULL,
  work_order_id text NOT NULL,
  check_type text NOT NULL,
  result text NOT NULL CHECK (result IN ('pass', 'fail', 'pending')),
  inspector text NOT NULL,
  notes text,
  checked_at timestamptz NOT NULL
);

-- Enable Row Level Security
ALTER TABLE quality_control ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated users
CREATE POLICY "Authenticated users can view all quality checks"
  ON quality_control
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert quality checks"
  ON quality_control
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update quality checks"
  ON quality_control
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete quality checks"
  ON quality_control
  FOR DELETE
  TO authenticated
  USING (true);

-- Create policies for anonymous users (if you want to allow anonymous access)
CREATE POLICY "Anonymous users can view all quality checks"
  ON quality_control
  FOR SELECT
  TO anon
  USING (true);

CREATE POLICY "Anonymous users can insert quality checks"
  ON quality_control
  FOR INSERT
  TO anon
  WITH CHECK (true);

CREATE POLICY "Anonymous users can update quality checks"
  ON quality_control
  FOR UPDATE
  TO anon
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Anonymous users can delete quality checks"
  ON quality_control
  FOR DELETE
  TO anon
  USING (true);